#!/bin/sh
# Rsync photos from my camera's SD card
# for Android 8.1 (LineageOS 15)
trap 'echo finished with status $?' 0
set -e
set -x
destination=/storage/emulated/0/CanonStuart12
mkdir -p $destination
for volume in /mnt/media_rw/[0-9A-F][0-9A-F][0-9A-F][0-9A-F]-[0-9A-F][0-9A-F][0-9A-F][0-9A-F]
do
    rsync --partial --times --recursive --include='*/' --include='*.JPG' --exclude='*' $volume/DCIM/1??CANON/ $destination/.
    #umount $volume
done
for f in $destination/*
do
    am broadcast -a android.intent.action.MEDIA_SCANNER_SCAN_FILE -d "file://$f"
done
